"""web crawler

Revision ID: cd1d987e33e9
Revises: 
Create Date: 2025-03-13 12:13:26.098316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd1d987e33e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_tasks',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('seeds', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('incoming_links', sa.Integer(), server_default='0', nullable=False),
    sa.Column('words_count', mysql.BIGINT(unsigned=True), server_default='0', nullable=False),
    sa.Column('last_crawled', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('word', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('links',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('from_page_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('to_page_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['from_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_words',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('page_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('word_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('occurence', mysql.BIGINT(unsigned=True), server_default='1', nullable=False),
    sa.Column('frequency', mysql.FLOAT(unsigned=True), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_words')
    op.drop_table('links')
    op.drop_table('words')
    op.drop_table('pages')
    op.drop_table('crawl_tasks')
    # ### end Alembic commands ###
